"""create periods table

Revision ID: 86da55a7e986
Revises: 409e08cf7c09
Create Date: 2026-09-22 11:56:55.842364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86da55a7e986'
down_revision: Union[str, Sequence[str], None] = '409e08cf7c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('goal_direction', sa.Enum('LOSS', 'GAIN', 'MAINTENANCE', name='goaldirection'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periods_end_date'), 'periods', ['end_date'], unique=False)
    op.create_index(op.f('ix_periods_start_date'), 'periods', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periods_start_date'), table_name='periods')
    op.drop_index(op.f('ix_periods_end_date'), table_name='periods')
    op.drop_table('periods')
    # ### end Alembic commands ###
